name: Update and upload
on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Pywikibot
      run: >
        git clone https://gerrit.wikimedia.org/r/pywikibot/core.git &&
        cd core &&
        git submodule update --init &&
        cd .. &&
        mv pywikibot/* core/ && rmdir pywikibot && mv core pywikibot
    - name: Write credentials from secrets
      run: >
       sed -i ''s/PYWIKIBOT_USER/${{ secrets.PYWIKIBOT_USER }}/g'' pywikibot/user-password.py &&
       sed -i ''s/PYWIKIBOT_PASS/${{ secrets.PYWIKIBOT_PASS }}/g'' pywikibot/user-password.py
    - run: pip install requests
    - run: python run.py -p Taiwan
    - name: Upload new media
      run: >
        python pwb.py login -all &&
        python pwb.py upload -filename:"File:COVID-19_outbreak_Taiwan_per_capita_cases_map.svg" -keep
        -summary:"Update map via GitHub Actions at littlebtc/covid-19-wikimedia-maps" -ignorewarn ../results/Taiwan.svg &&
        python pwb.py login -logout
      working-directory: ./pywikibot
